const fishData = [
    // LAKE FISH
    {
        name: 'Goldfish',
        type: 'fish',
        modelPath: 'src/objects/fish/goldfish.png',
        sellPrice: 100,
        rarityLevel: 4,
        biome: 'lake',
        caught: true,
    },
    {
        name: 'Trout',
        type: 'fish',
        modelPath: 'src/objects/fish/trout.png',
        sellPrice: 100,
        rarityLevel: 4,
        biome: 'lake',
        caught: true,
    },
    {
        name: 'Largemouth Bass',
        type: 'fish',
        modelPath: 'src/objects/fish/largemouth.png',
        sellPrice: 200,
        rarityLevel: 3,
        biome: 'lake',
        caught: true,
    },
    {
        name: 'Crappie',
        type: 'fish',
        modelPath: 'src/objects/fish/crappie.png',
        sellPrice: 200,
        rarityLevel: 3,
        biome: 'lake',
        caught: true,
    },
    {
        name: 'Gold Fish',
        type: 'fish',
        modelPath: 'src/objects/fish/gold-fish.png',
        sellPrice: 500,
        rarityLevel: 2,
        biome: 'lake',
        caught: true,
    },
    {
        name: 'Diamond Darter',
        type: 'fish',
        modelPath: 'src/objects/fish/diamond-darter.png',
        sellPrice: 500,
        rarityLevel: 1,
        biome: 'lake',
        caught: true,
    },

    // RIVER FISH
    {
        name: 'Chub',
        type: 'fish',
        modelPath: 'src/objects/fish/chub.png',
        sellPrice: 100,
        rarityLevel: 4,
        biome: 'global',
        caught: true,
    },
    {
        name: 'Bullhead',
        type: 'fish',
        modelPath: 'src/objects/fish/bullhead.png',
        sellPrice: 100,
        rarityLevel: 4,
        biome: 'global',
        caught: true,
    },
    {
        name: 'Minnow',
        type: 'fish',
        modelPath: 'src/objects/fish/blankFish.png',
        sellPrice: 200,
        rarityLevel: 3,
        biome: 'global',
        caught: true,
    },
    {
        name: 'Stone Loach',
        type: 'fish',
        modelPath: 'src/objects/fish/blankFish.png',
        sellPrice: 300,
        rarityLevel: 2,
        biome: 'global',
        caught: true,
    },
    {
        name: 'Rainbow Trout',
        type: 'fish',
        modelPath: 'src/objects/fish/blankFish.png',
        sellPrice: 500,
        rarityLevel: 1,
        biome: 'global',
        caught: true,
    },

    // SEA FISH
    {
        name: 'Mackarel',
        type: 'fish',
        modelPath: 'src/objects/fish/blankFish.png',
        sellPrice: 100,
        rarityLevel: 4,
        biome: 'sea',
        caught: true,
    },
    {
        name: 'Herring',
        type: 'fish',
        modelPath: 'src/objects/fish/blankFish.png',
        sellPrice: 200,
        rarityLevel: 3,
        biome: 'sea',
        caught: true,
    },
    {
        name: 'Pupfish',
        type: 'fish',
        modelPath: 'src/objects/fish/blankFish.png',
        sellPrice: 400,
        rarityLevel: 2,
        biome: 'sea',
        caught: true,
    },
    {
        name: 'Tigerfish',
        type: 'fish',
        modelPath: 'src/objects/fish/blankFish.png',
        sellPrice: 800,
        rarityLevel: 1,
        biome: 'sea',
        caught: true,
    },
    {
        name: 'Catfish',
        type: 'fish',
        modelPath: 'src/objects/fish/blankFish.png',
        sellPrice: 1000,
        rarityLevel: 1,
        biome: 'sea',
        caught: true,
    },

    // TRASH
    // {
    //     name: "Boot",
    //     type: "trash",
    //     modelPath: "",
    //     sellPrice: 10,
    //     rarityLevel: 5,
    //     biome: "river",
    //     caught: true,
    // },
    // {
    //     name: "Can",
    //     type: "trash",
    //     modelPath: "",
    //     sellPrice: 5,
    //     rarityLevel: 5,
    //     biome: "sea",
    //     caught: true
    // },
];

export default fishData;
